# Generated by Django 2.1.5 on 2019-03-02 18:44

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190302_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(upload_to=posts.models.get_post_thumbnail, max_length=255),
        ),
    ]
