# Generated by Django 2.1.5 on 2019-03-04 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumbnail',
        ),
    ]
