# Generated by Django 2.1.5 on 2019-03-04 12:02

from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=posts.models.get_post_thumbnail),
        ),
    ]
