# Generated by Django 2.1.5 on 2019-03-04 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190304_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_comments', related_query_name='liked_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
