# Generated by Django 2.1.5 on 2019-03-08 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_post_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcomment',
            name='likes',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='voted_comments', related_query_name='voted_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
