# Generated by Django 2.1.5 on 2019-02-11 11:08

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190211_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=users.models.get_default_avatar_path, max_length=255, upload_to=users.models.get_avatar_path),
        ),
    ]
